spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_DATABASE_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  redirectUri: ${KAKAO_REDIRECT_URL}

cors:
  allowedOrigin: ${DEFAULT_URL}


server:
  port: 8080

