spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_DATABASE_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  redirectUri: ${KAKAO_REDIRECT_URL}

#cors:
#  allowedOrigin: ${DEFAULT_URL}


server:
  port: 8080

logging:
  level:
    root: INFO  # 루트 로깅 레벨을 INFO로 설정
    com.today_solution_server.demo: INFO  # 특정 패키지에 대한 로깅 레벨 설정 (예: demo 패키지)
    com.today_solution_server.demo.controller: DEBUG